#!/usr/bin/env bash
# Project verification cockpit — generated by verification-cockpit skill.
# Usage: tmux-layout.sh [directory]
set -euo pipefail

DIR="${1:-.}"
SCRIPT_NAME="project-verify-layout"
VERIFY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR" && pwd)"

if ! command -v tmux >/dev/null 2>&1; then
    echo "$SCRIPT_NAME: tmux not found" >&2
    exit 1
fi

if [ -z "${TMUX:-}" ]; then
    echo "$SCRIPT_NAME: must run inside tmux" >&2
    exit 1
fi

# shellcheck source=/dev/null
source "$HOME/.config/shell/bin/lib/verify-launch.sh"

SESSION="$(tmux display-message -p '#{session_name}')"
tmux set-option -t "$SESSION" @workflow_dir "$ROOT"
tmux set-option -t "$SESSION" @workflow_mode verify

PROJECT_NAME="PROJECT_NAME"
RISK_PROFILE="MEDIUM"

verify_apply_theme "$SESSION" "$PROJECT_NAME" "$RISK_PROFILE" "$VERIFY_DIR/tmux-theme.conf"

if tmux list-windows -F '#{window_name}' 2>/dev/null | grep -qx 'verify'; then
    tmux select-window -t 'verify'
else
    tmux new-window -n verify -c "$ROOT"

    # Pane 1: git (right)
    tmux split-window -h -t 'verify' -c "$ROOT" -p 42
    if command -v lazygit >/dev/null 2>&1; then
        verify_launch_pane 'verify.1' monitor 'GIT' "$ROOT" lazygit
    fi

    # Pane 2: watch (left column bottom)
    tmux select-pane -t 'verify.0'
    tmux split-window -v -t 'verify.0' -c "$ROOT" -p 45
    verify_launch_pane 'verify.2' watch 'WATCH' "$ROOT" 'pnpm test --watch'

    # Pane 3: files (below watch)
    tmux select-pane -t 'verify.2'
    tmux split-window -v -t 'verify.2' -c "$ROOT" -p 40
    if command -v yazi >/dev/null 2>&1; then
        verify_launch_pane 'verify.3' monitor 'FILES' "$ROOT" yazi
    fi

    # Pane 4: sys (below files)
    tmux select-pane -t 'verify.3'
    tmux split-window -v -t 'verify.3' -c "$ROOT" -p 35
    if command -v btop >/dev/null 2>&1; then
        verify_launch_pane 'verify.4' monitor 'SYS' "$ROOT" btop
    fi

    # Pane 0: console
    verify_launch_pane 'verify.0' monitor 'CMD' "$ROOT" ''

    tmux select-pane -t 'verify.0'
    tmux select-layout -t verify main-vertical 2>/dev/null || true
fi

verify_maybe_rescan "$SESSION" 'verify.0'
tmux select-pane -t 'verify.0'
